cmake_minimum_required(VERSION 3.20)

# Kumpulan seluruh contoh tutorial Win32 & DWM
add_subdirectory(01-hello-window)
add_subdirectory(02-input-keyboard-mouse)
add_subdirectory(03-gdi-drawing)
add_subdirectory(04-double-buffering)
add_subdirectory(05-dpi-aware)
add_subdirectory(06-dwm-dark-mode)
add_subdirectory(07-custom-titlebar)
add_subdirectory(final-app)
